// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC24KotwT-r4dzJzucZJQqkKvrLXu3CUqs',
    appId: '1:548611691877:android:f7bb169d9cac079e207d8c',
    messagingSenderId: '548611691877',
    projectId: 'condoplantadvisor',
    storageBucket: 'condoplantadvisor.firebasestorage.app',
  );

  // TODO: Add iOS config if deploying to iOS (run `flutterfire configure`)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '548611691877',
    projectId: 'condoplantadvisor',
    storageBucket: 'condoplantadvisor.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_IOS_CLIENT_ID',
    iosBundleId: 'com.company.plantify',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: '548611691877',
    projectId: 'condoplantadvisor',
    storageBucket: 'condoplantadvisor.firebasestorage.app',
    authDomain: 'condoplantadvisor.firebaseapp.com',
  );
}
